baseURL = "https://hpvstudiomondello.it"
themesDir = "themes"
theme = "hugo-serif-theme"
languageCode = "it-IT"
title = "Dott. Mondello Placido"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  # In most cases you will only want to set the google_analytics_id OR the google_tag_manager_id. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = "" # implementato nel cookie banner
  google_tag_manager_id = ""
  favicon = "favicon-32x32.svg"

  [params.homepage]
    show_contact_box = true      # show / hide the contaxt box on the homepage
    show_services_button = false # show / hide the "view all services" button

  [params.logo]
    mobile = "images/logo/hpv-studio-mondello.svg"
    mobile_height = "60px"
    desktop = "images/logo/hpv-studio-mondello.svg"
    desktop_height = "60px"
    alt = "logo HPV Studio del Dott. Mondello Placido"

  [params.fonts]
    # sets the google font link in layouts/partials/google-fonts.html
    google_fonts = 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600&family=Source+Sans+Pro:wght@400;700&display=swap'
    heading = "Playfair Display"
    base = "Source Sans Pro"

  [params.colors]
    primary = "#f24088"
    black = "#2f2f41"
    white = "#ffffff"
    white_offset = "#f6f7ff"
    grey = "#5C5A5A"

  [params.seo]
    meta_twitter_site = "@hpvstudiomondello"
    meta_twitter_creator = "@hpvstudiomondello"
    meta_og_image = "hpv-studio-dott-mondello-screenshot.png"

  [params.services]
    summary_truncate = 80 # How many characters to include in the summary of the HOME page services before truncating
    summary_large_truncate = 160 # How many characters to include in the summary of Servizi services before truncating

  [params.team]
    summary_large_truncate = 120 # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    ordinemedici_text = 'Ordine dei Medici di Messina 5175 - C.ENPAM 300073231W'
    copyright_text = 'Copyright © <span id="currentYear"></span> Dott. Placido Mondello. Tutti i diritti sono riservati.'

[menu]
  # Main Menu
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  

  [[menu.main]]
    name = "Dr. Mondello Placido"
    url = "/Dott-Mondello-Placido/"
    weight = 2

  [[menu.main]]
    name = "Centro HPV"
    url = "/centro-hpv/"
    weight = 3

  [[menu.main]]
    name = "Visite e Terapie"
    url = "/visite-terapie/"
    weight = 4

  [[menu.main]]
    name = "Contatti"
    url = "/contatti/"
    weight = 5

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.footer]]
    name = "Dr. Mondello Placido"
    url = "/Dott-Mondello-Placido/"
    weight = 2

  [[menu.footer]]
    name = "Centro HPV"
    url = "/centro-hpv/"
    weight = 3

  [[menu.footer]]
    name = "Visite e Terapie"
    url = "/visite-terapie/"
    weight = 4

  [[menu.footer]]
    name = "Contatti"
    url = "/contatti/"
    weight = 5

  [[menu.footer]]
    name = "Privacy Policy"
    url = "/privacy-policy/"
    weight = 6
